FROM alpine:3

ARG CLOUDFLARED_VERSION=2020.11.11
ARG CLOUDFLARED_BIN=https://github.com/cloudflare/cloudflared/releases/download

RUN \
  set -x && \
  apk update && \
  apk upgrade && \
  apk add tzdata ca-certificates libcap bind-tools curl libc6-compat && \
  curl -L -o /usr/local/bin/cloudflared ${CLOUDFLARED_BIN}/${CLOUDFLARED_VERSION}/cloudflared-linux-armv6 && \
  chmod ugo+x /usr/local/bin/cloudflared && \
  setcap 'cap_net_bind_service=+ep' /usr/local/bin/cloudflared 

USER nobody

ENV TUNNEL_DNS_ADDRESS "0.0.0.0"
ENV TUNNEL_DNS_PORT "53"
ENV TUNNEL_METRICS "0.0.0.0:10080"
ENV TUNNEL_DNS_UPSTREAM "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"

ENTRYPOINT ["cloudflared", "--no-autoupdate"]

CMD ["proxy-dns"]

RUN ["cloudflared", "--version"]
